"use client";

import { useEffect, useState } from "react";
import { Container } from "@/components/layout/Container";
import { Header } from "@/components/layout/Header";
import { AuditRecord } from "@/lib/audit/types";
import Link from "next/link";
import { ArrowRight, Clock, FileText, TrendingDown } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function HistoryPage() {
  const [history, setHistory] = useState<AuditRecord[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const historyJson = localStorage.getItem("ledger_audit_history");
    if (historyJson) {
      try {
        setHistory(JSON.parse(historyJson));
      } catch (e) {
        console.error("Failed to parse audit history");
      }
    }
    setLoading(false);
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col font-sans">
      <Header />
      
      <main className="flex-1 py-20 bg-grid-pattern bg-[size:40px_40px]">
        <Container>
          <div className="max-w-5xl mx-auto">
            <div className="mb-12 space-y-4">
              <div className="inline-flex items-center border border-border bg-background px-3 py-1 text-xs font-mono font-bold uppercase tracking-widest text-foreground shadow-sm">
                <span className="flex h-1.5 w-1.5 bg-primary mr-2"></span>
                Archival Ledger
              </div>
              <h1 className="text-5xl font-semibold tracking-tighter">Audit History</h1>
              <p className="text-xl text-muted-foreground max-w-2xl">
                A persistent record of all infrastructure reconciliations and optimization reports generated by LedgerAI.
              </p>
            </div>

            {loading ? (
              <div className="py-20 text-center font-mono text-muted-foreground animate-pulse">
                Accessing archives...
              </div>
            ) : history.length === 0 ? (
              <div className="py-20 border border-border bg-card p-12 text-center space-y-8">
                <div className="size-16 bg-muted mx-auto flex items-center justify-center">
                  <FileText className="h-8 w-8 text-muted-foreground" />
                </div>
                <div className="space-y-2">
                  <h2 className="text-2xl font-semibold tracking-tight">No historical records found</h2>
                  <p className="text-muted-foreground">Initialize your first audit to begin tracking your infrastructure spend.</p>
                </div>
                <Link href="/onboarding">
                  <Button size="lg" className="h-14 px-8 uppercase tracking-widest font-bold shadow-none">
                    Initialize Audit <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
              </div>
            ) : (
              <div className="border border-border bg-card shadow-sm divide-y divide-border overflow-hidden">
                <div className="grid grid-cols-12 gap-4 px-8 py-4 bg-muted/30 text-xs font-mono font-bold uppercase tracking-widest text-muted-foreground border-b border-border">
                  <div className="col-span-3">Timestamp</div>
                  <div className="col-span-2">Audit ID</div>
                  <div className="col-span-2">Score</div>
                  <div className="col-span-3 text-right">Savings (Annual)</div>
                  <div className="col-span-2 text-right">Status</div>
                </div>
                
                {history.map((record) => (
                  <Link 
                    key={record.id} 
                    href={`/dashboard?id=${record.id}`}
                    className="grid grid-cols-12 gap-4 px-8 py-8 items-center hover:bg-muted/50 transition-colors group"
                  >
                    <div className="col-span-3 flex items-center gap-3">
                      <Clock className="h-4 w-4 text-muted-foreground group-hover:text-primary transition-colors" />
                      <div className="flex flex-col">
                        <span className="font-mono text-sm">
                          {new Date(record.timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                        </span>
                        <span className="text-[10px] text-muted-foreground font-mono">
                          {new Date(record.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false })}
                        </span>
                      </div>
                    </div>
                    <div className="col-span-2 font-mono font-bold text-foreground">
                      {record.id}
                    </div>
                    <div className="col-span-2">
                      <div className="flex items-center gap-2">
                        <div className="h-1.5 flex-1 bg-muted overflow-hidden">
                          <div 
                            className="h-full bg-primary transition-all duration-1000" 
                            style={{ width: `${record.result.optScore}%` }}
                          />
                        </div>
                        <span className="font-mono text-sm font-bold">{record.result.optScore}</span>
                      </div>
                    </div>
                    <div className="col-span-3 text-right">
                      <div className="flex flex-col items-end">
                        <span className="font-mono font-bold text-primary">
                          {record.result.annualSavings.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 })}
                        </span>
                        <span className="text-[10px] text-muted-foreground font-mono flex items-center gap-1 uppercase tracking-tighter">
                          <TrendingDown className="h-2 w-2" /> {record.result.leakagePercent}% Leakage
                        </span>
                      </div>
                    </div>
                    <div className="col-span-2 text-right">
                      <span className="inline-flex items-center border border-primary/20 bg-primary/10 px-2 py-0.5 text-[10px] font-mono font-bold text-primary uppercase tracking-widest">
                        Archived
                      </span>
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </Container>
      </main>
    </div>
  );
}
